import 'package:flutter/material.dart';
import 'package:get/get.dart';

class LocalizationService extends Translations {
  // Supported languages
  static final List<Locale> supportedLocales = [
    const Locale('en', 'US'),
    const Locale('sv', 'SE'),
  ];

  // Default language
  static const fallbackLocale = Locale('en', 'US');

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "next": "Next",
      "skip": "SKIP",
      "slider_heading_1": "Let’s Get Started",
      "slider_content_1":
      "\"Start your journey today by discovering a world of preloved toys for your little one. Whether you’re looking to buy or sell, we make it easy to find quality kids products and enjoy fast delivery!\"",
      "slider_heading_2": "Your Onboarding Journey Begins!",
      "slider_content_2":
      "\"Capturing and sharing your child’s gently used toys has never been simpler! Snap a picture, list your item, and connect with other families who are excited to buy and sell the best kids' products.\"",
      "slider_heading_3": "Your First Steps To Success",
      "slider_content_3":
      "\"Ready to ship your preloved toys to happy homes? With our easy process and fast delivery, you’re not just selling – you’re making another family’s day while decluttering with ease!\"",
      "buying_and": "Buying &",
      "selling_pre_loved": "Selling \nPre-loved \n",
      "items": "Items",
      "get_started": "GET STARTED",
      "language": "Language",
      "swedish": "Swedish",
      "english": "English",
      "login": "Login",
      "sign_up": "Sign Up",
      "continue_with_facebook": "Continue with Facebook",
      "continue_with_apple": "Continue with Apple",
      "continue_with_google": "Continue with Google",
      "or_continue_with": "Or Continue with",
      "email": " email",
      "sign_in": "Sign In",
      "welcome_back": "Welcome Back",
      "sign_in_to_continue": "Sign in to continue",
      "email_hint": "Email",
      "password_hint": "Password",
      "continue": "CONTINUE",
      "dont_have_account": "Don't have an account?",
      "email_required": "Email is required",
      "valid_email": "Enter a valid email",
      "password_required": "Password is required",
      "password_min_length": "Password must be at least 8 characters long",
      "signup": "Signup",
      "welcome": "Welcome",
      "email_or_phone": "Email or phone number",
      "password": "Password",
      "confirm_password": "Confirm Password",
      "confirm_password_required": "Confirm password is required",
      "password_mismatch": "Passwords do not match",
      "password_length": "Password must be at least 8 characters long",
      "password_capital_letter": "Password must contain at least one capital letter",
      "password_number": "Password must contain at least one number",
      "password_special_char": "Password must contain at least one special character",
      "already_have_account": "Already have an account?",
      "email_phone_required": "Email or phone number is required",
      "valid_email_phone": "Enter a valid email or phone number",
      //Home Screen
      "products": "Products",
      "members": "Members",
      "search_hint": "Search for desired products here",
      "no_products_found": "No products found",
      "no_members_found": "No members found",
      "unknown_user": "Unknown User",
      "home": "Home",
      "search": "Search",
      "sell": "Sell",
      "chat": "Chat",
      "profile": "Profile",
      "explore": "Explore",
      "categories": "Categories",
      "cart": "Cart",
      "details": "Details",
      "no_categories_found": "No categories found",
      "select_category": "Select the category",
      "chats": "Chats",
      "no_chats_available": "No chats available.",
      "buying": "Buying",
      "selling": "Selling",
      "followers": "Followers",
      "following": "Following",
      "sales": "Sales",
      "purchases": "Purchases",
      "active": "Active",
      "sold": "Sold",
      "loading": "Loading...",
      "failed_to_update_follow": "Failed to update follow status",
      "follow": "Follow",
      "following_status": "Following",
      "my_profile": "My Profile",
      "transaction_history": "Transaction History",
      "my_order": "My Order",
      "my_reviews": "My Reviews",
      "faqs": "FAQs",
      "my_shop_order": "My Shop Order",
      "my_wallet": "My Wallet",
      "contact_us": "Contact Us",
      "about_us": "About Us",
      "help_center": "Help Center",
      "terms_conditions": "Terms & Conditions",
      "privacy_policy": "Privacy Policy",
      "delete_account": "Delete Account",
      "logout": "Logout",
      //Forum
      'forum_title': 'Forum',
      'no_posts': 'No posts available',
      'edit': 'Edit',
      'delete': 'Delete',
      'refreshing': 'Refreshing...',
      'liked_post': 'Liked Post',
      'new_post': 'New Post',
      'edit_post': 'Edit Post',
      'description': 'Description',
      'tags': 'Tags',
      'add_tag': 'Add Tag',
      'post_now': 'Post Now',
      'update_post': 'Update Post',
      'enter_tags': 'Enter tags separated by space..',
      'please_enter_valid_tags': 'Please enter valid tags.',
      'view_post': 'View Post',
      'add_comment': 'Add Comment',
      'write_comment_hint': 'Write your comment...',
      'please_enter_comment': 'Please enter a comment.',
      'post_button': 'Post',
      'add_reply': 'Reply to Comment',
      'write_reply_hint': 'Write your reply...',
      'please_enter_reply': 'Please enter a reply.',
      'edit_comment': 'Edit Comment',
      'edit_comment_hint': 'Edit your comment...',
      'save_button': 'Save',
      'edit_reply': 'Edit Reply',
      'edit_reply_hint': 'Edit your reply...',
      'like_count': 'Likes',
      'comment_count': 'Comments',
      'replies_count': 'Replies',
      'reply': 'Reply',
      'subcategory_title': 'See all in @title for',
      'subcategory_back': 'Back',
      //Add Product
      "edit_product": "Edit Product",
      "add_product": "Add Product",
      "update_details": "Update your product details",
      "almost_there": "You’re almost there!",
      "title_label": "Title",
      "title_hint": "Title here...",
      "subcategory_label": "Subcategory",
      "select_subcategory": "Select Subcategory",
      "description_label": "Description",
      "description_hint": "Write something here...",
      "gallery": "Gallery",
      "camera": "Camera",
      "price_label": "Price",
      "price_hint": "\$100",
      "update_now": "Update Now",
      //Chat
      "chat_title": "Chat with {name}",
      "enter_message": "Enter message",
      "write_message_here": "Write your message here",
      "message_empty_error": "Message cannot be empty.",
      "offer_text": "Your Offer",
      //Transaction
      "transaction_history_title": "Transaction History",
      "no_transactions": "No transaction history available.",
      "status_pending": "Pending",
      "status_approved": "Approved",
      "status_rejected": "Rejected",
      "transaction_card_details": "*****{lastFour} - {date}",
      "transaction_amount": "{amount} {currency}",
      //Order
      "my_orders_title": "My Orders",
      "no_orders_found": "No orders found",
      "order_id": "Order# ",
      "order_status_paid": "Paid",
      "order_status_pending": "Pending",
      "faqs_title": "FAQs",
      "my_shop_orders": "My Shop Orders",
      //Wallet
      "balance": "Balance",
      "make_withdraw": "Make Withdraw",
      "withdrawn": "Withdrawn",
      "pending": "Pending",
      "starting_balance": "Balance",
      "history": "History",
      "select_withdrawal_method": "Select Withdrawal Method",
      "bank_transfer": "Bank Transfer",
      "swish": "Swish",
      "paypal": "PayPal",
      "withdraw_to_bank_account": "Withdraw to bank account",
      //Contact Us
      "how_can_we_help": "How can we help you?",
      "help_description": "It looks like you have problems with our systems. We are here to help you, so please get in touch with us.",
      "call": "Call",
      "unfollow": "Unfollow",
      "order_status_shipped": "Shipped",
      "order_status_delivered": "Delivered",
      "order_status_received": "Received",
      "order_status_cancelled": "Cancelled",
      "order_status_refunded": "Refunded",
      "buy_now": "BUY NOW",
      "chat_now": "CHAT NOW",
      "make_an_offer": "MAKE AN OFFER",
      "success": "Success",
      "checkout_success": "Checkout completed successfully",
      "error": "Error",
      "checkout_failed": "Checkout failed: @error",
      "payment_failed": "Payment failed: @error",
      "offer_failed": "Failed to send offer: @error"
    },
    'sv_SE': {
      "next": "Nästa",
      "skip": "HOPPA ÖVER",
      "slider_heading_1": "Kom igång",
      "slider_content_1":
      "\"Börja din resa idag genom att upptäcka en värld av begagnade leksaker för ditt barn. Oavsett om du vill köpa eller sälja gör vi det enkelt att hitta kvalitetsprodukter för barn och njuta av snabb leverans!\"",
      "slider_heading_2": "Din introduktionsresa börjar!",
      "slider_content_2":
      "\"Att fånga och dela ditt barns försiktigt använda leksaker har aldrig varit enklare! Ta en bild, lista din artikel och anslut med andra familjer som är glada att köpa och sälja de bästa barnprodukterna.\"",
      "slider_heading_3": "Dina första steg till framgång",
      "slider_content_3":
      "\"Redo att skicka dina begagnade leksaker till lyckliga hem? Med vår enkla process och snabba leverans säljer du inte bara – du gör en annan familjs dag samtidigt som du rensar med lätthet!\"",
      "buying_and": "Köper &",
      "selling_pre_loved": "Säljer \nBegagnade \n",
      "items": "Saker",
      "get_started": "KOM IGÅNG",
      "language": "Språk",
      "swedish": "Svenska",
      "english": "Engelska",
      "login": "Logga in",
      "sign_up": "Registrera dig",
      "continue_with_facebook": "Fortsätt med Facebook",
      "continue_with_apple": "Fortsätt med Apple",
      "continue_with_google": "Fortsätt med Google",
      "or_continue_with": "Eller fortsätt med",
      "email": " e-post",
      "sign_in": "Logga in",
      "welcome_back": "Välkommen tillbaka",
      "sign_in_to_continue": "Logga in för att fortsätta",
      "email_hint": "E-post",
      "password_hint": "Lösenord",
      "continue": "FORTSÄTT",
      "dont_have_account": "Har du inget konto?",
      "email_required": "E-post krävs",
      "valid_email": "Ange en giltig e-postadress",
      "password_required": "Lösenord krävs",
      "password_min_length": "Lösenordet måste vara minst 8 tecken långt",
      "signup": "Registrera dig",
      "welcome": "Välkommen",
      "email_or_phone": "E-post eller telefonnummer",
      "password": "Lösenord",
      "confirm_password": "Bekräfta lösenord",
      "confirm_password_required": "Bekräfta lösenord krävs",
      "password_mismatch": "Lösenorden matchar inte",
      "password_length": "Lösenordet måste vara minst 8 tecken långt",
      "password_capital_letter": "Lösenordet måste innehålla minst en versal",
      "password_number": "Lösenordet måste innehålla minst ett nummer",
      "password_special_char": "Lösenordet måste innehålla minst ett specialtecken",
      "already_have_account": "Har du redan ett konto?",
      "email_phone_required": "E-post eller telefonnummer krävs",
      "valid_email_phone": "Ange en giltig e-postadress eller telefonnummer",
      //Home Screen
      "products": "Produkter",
      "members": "Medlemmar",
      "search_hint": "Sök efter önskade produkter här",
      "no_products_found": "Inga produkter hittades",
      "no_members_found": "Inga medlemmar hittades",
      "unknown_user": "Okänd användare",
      "home": "Hem",
      "search": "Sök",
      "sell": "Sälj",
      "chat": "Chatt",
      "profile": "Profil",
      "explore": "Utforska",
      "categories": "Kategorier",
      "cart": "Kundvagn",
      "details": "Detaljer",
      "no_categories_found": "Inga kategorier hittades",
      "select_category": "Välj kategori",
      "chats": "Chattar",
      "no_chats_available": "Inga chattar tillgängliga.",
      "buying": "Köper",
      "selling": "Säljer",
      "followers": "Följare",
      "following": "Följer",
      "sales": "Försäljning",
      "purchases": "Köp",
      "active": "Aktiv",
      "sold": "Såld",
      "loading": "Laddar...",
      "failed_to_update_follow": "Misslyckades med att uppdatera följestatus",
      "follow": "Följ",
      "following_status": "Följer",
      "my_profile": "Min Profil",
      "transaction_history": "Transaktionshistorik",
      "my_order": "Min Order",
      "my_reviews": "Mina Recensioner",
      "faqs": "Vanliga Frågor",
      "my_shop_order": "Min Butiksorder",
      "my_wallet": "Min Plånbok",
      "contact_us": "Kontakta Oss",
      "about_us": "Om Oss",
      "help_center": "Hjälpcenter",
      "terms_conditions": "Villkor",
      "privacy_policy": "Integritetspolicy",
      "delete_account": "Ta bort Konto",
      "logout": "Logga Ut",
      //Forum
      'forum_title': 'Forum',
      'no_posts': 'Inga inlägg tillgängliga',
      'edit': 'Redigera',
      'delete': 'Radera',
      'refreshing': 'Uppdaterar...',
      'liked_post': 'Gillade inlägg',
      'new_post': 'Nytt inlägg',
      'edit_post': 'Redigera inlägg',
      'description': 'Beskrivning',
      'tags': 'Taggar',
      'add_tag': 'Lägg till tagg',
      'post_now': 'Publicera nu',
      'update_post': 'Uppdatera inlägg',
      'enter_tags': 'Ange taggar separerade med mellanslag..',
      'please_enter_valid_tags': 'Ange giltiga taggar.',
      'view_post': 'Visa inlägg',
      'add_comment': 'Lägg till kommentar',
      'write_comment_hint': 'Skriv din kommentar...',
      'please_enter_comment': 'Vänligen skriv en kommentar.',
      'post_button': 'Publicera',
      'add_reply': 'Svara på kommentar',
      'write_reply_hint': 'Skriv ditt svar...',
      'please_enter_reply': 'Vänligen skriv ett svar.',
      'edit_comment': 'Redigera kommentar',
      'edit_comment_hint': 'Redigera din kommentar...',
      'save_button': 'Spara',
      'edit_reply': 'Redigera svar',
      'edit_reply_hint': 'Redigera ditt svar...',
      'like_count': 'Gillar',
      'comment_count': 'Kommentarer',
      'replies_count': 'Svar',
      'reply': 'Svara',
      'subcategory_title': 'Visa allt i @title för',
      'subcategory_back': 'Tillbaka',
      //Add Product
      "edit_product": "Redigera produkt",
      "add_product": "Lägg till produkt",
      "update_details": "Uppdatera dina produktuppgifter",
      "almost_there": "Du är nästan där!",
      "title_label": "Titel",
      "title_hint": "Titel här...",
      "subcategory_label": "Underkategori",
      "select_subcategory": "Välj underkategori",
      "description_label": "Beskrivning",
      "description_hint": "Skriv något här...",
      "gallery": "Galleri",
      "camera": "Kamera",
      "price_label": "Pris",
      "price_hint": "100 kr",
      "update_now": "Uppdatera nu",
      //Chat
      "chat_title": "Chatta med {name}",
      "enter_message": "Ange meddelande",
      "write_message_here": "Skriv ditt meddelande här",
      "message_empty_error": "Meddelandet kan inte vara tomt.",
      "offer_text": "Ditt erbjudande",
      //Transaction
      "transaction_history_title": "Transaktionshistorik",
      "no_transactions": "Ingen transaktionshistorik tillgänglig.",
      "status_pending": "Väntande",
      "status_approved": "Godkänd",
      "status_rejected": "Avslagen",
      "transaction_card_details": "*****{lastFour} - {date}",
      "transaction_amount": "{amount} {currency}",
      //Order
      "my_orders_title": "Mina Beställningar",
      "no_orders_found": "Inga beställningar hittades",
      "order_id": "Beställning# ",
      "order_status_paid": "Betalad",
      "order_status_pending": "Väntande",
      "faqs_title": "Vanliga frågor",
      "my_shop_orders": "Mina Butiksbeställningar",
      //Wallet
      "balance": "Saldo",
      "make_withdraw": "Gör ett uttag",
      "withdrawn": "Uttag",
      "pending": "Väntar",
      "starting_balance": "Startsaldo",
      "history": "Historik",
      "select_withdrawal_method": "Välj uttagsmetod",
      "bank_transfer": "Banköverföring",
      "swish": "Swish",
      "paypal": "PayPal",
      //Contact Us
      "how_can_we_help": "Hur kan vi hjälpa dig?",
      "help_description": "Det verkar som om du har problem med våra system. Vi är här för att hjälpa dig, så vänligen kontakta oss.",
      "call": "Ring",
      "unfollow": "Dejar de seguir",
      "order_status_shipped": "Skickad",
      "order_status_delivered": "Levererad",
      "order_status_received": "Mottagen",
      "order_status_cancelled": "Avbruten",
      "order_status_refunded": "Återbetald",
      "buy_now": "KÖP NU",
      "chat_now": "CHATTA NU",
      "make_an_offer": "GE ETT ERBJUDANDE",
      "success": "Framgång",
      "checkout_success": "Kassan slutförd framgångsrikt",
      "error": "Fel",
      "checkout_failed": "Kassan misslyckades: @error",
      "payment_failed": "Betalningen misslyckades: @error",
      "offer_failed": "Misslyckades med att skicka erbjudandet: @error"

    },
  };

  // Change locale dynamically
  static void changeLocale(String languageCode) {
    Locale locale = supportedLocales.firstWhere(
          (locale) => locale.languageCode == languageCode,
      orElse: () => fallbackLocale,
    );
    Get.updateLocale(locale);
  }
}
